### ISSUE TITLE
Gmail could not be shown the copied content properly

### ISSUE THREAD

**Issue by onur-degerli** [milan-hwj/ClipBoard#4]
When I copy a content and paste it in the Gmail, it is shown like in the screenshot.
Is this problem related to gmail or the library?

<img width="600" alt="screen shot 2017-06-05 at 23 18 59" src="https://cloud.githubusercontent.com/assets/959125/26801495/bd164db6-4a45-11e7-92ac-b208cb125a30.png">

**Comment by milan-hwj** [comment]
I can not reproduce the problem.
open "demo/performanceTest.html" in chrome, and click button "run".

![image](https://user-images.githubusercontent.com/13595913/26861230-1e79c404-4b75-11e7-95b9-5bc4b0f52d58.png)


Please show your copy content.
